version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:12.16'
    steps:
      - run:
          command: npm install
  deliver:
    docker:
      - image: 'cimg/node:12.16'
    steps:
      - run:
          command: ./jenkins/scripts/deliver.sh
      - run:
          command: ./jenkins/scripts/kill.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deliver:
          requires:
            - build