version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:12.16'
    steps:
      - checkout
      - run:
          command: cd home/circleci/project && npm install
  deliver:
    docker:
      - image: 'cimg/node:12.16'
    steps:
      - checkout
      - run:
          command: cd home/circleci/project 
            set -x
            npm start &
            sleep 1
            echo $! > .pidfile
            set +x
      - run:
          command: kill $(cat .pidfile)
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deliver:
          requires:
            - build